# Jekyll configuration

name: Cuaderno de bitácora
description: Life's a maze of twisty little passages, all alike

timezone: Europe/Madrid

# Url is currently only used only for the RSS feed in feed.xml
url: http://elgeekerrante.com

# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
baseurl: ""

share:
  facebook: true
  twitter: true
  gplus: true
  linkedin: false
  pinterest: false
  email: false

social:
  github: ""
  stackoverflow: ""
  linkedin: ""
  instagram: ""
  lastfm: ""
  rss: feed.xml

# Google Analytics key, leave blank to ignore
google_analytics_key:

# Google Tag Manager key
google_tagmanager_key: GTM-5HZL9VQ


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: elgeekerrante
comments: false

twitter:
  hastags:
    - EGE
    - podcast
  username: geek_errante

# Podcasting
podcast:
  url: http://elgeekerrante.com
  album_art: /images/ege_itunes_logo.jpg
  title: El Geek Errante
  owner: The Crew
  email: podcast@elgeekerrante.com
  category: Technology
  subcategory_one: Tech News
  explicit: "no"
  author: La tripulación de El Geek Errante
  keywords: geek,tecnologia,gpl,linux,software,hacking,unix
  description: "Bienvenidos a bordo del Geek Errante. Nuestra misión en cada episodio es llevar a ustedes, geeks y frikis de habla hispana, los comentarios técnicos más profundos, las noticias tecnológicas más interesantes, las opiniones más políticamente incorrectas y por qué no, un toque de humor geek. Cada semana El Doctor, Mr. Solo, HoloJorge y FuTuR3 llevarán a sus reproductores de MP3, a través de su transmisor subespacial, el contenido más geek de la podosfera en español. Esperamos que este viaje sea de su agrado."
  subtitle: Perdidos en el Multiverso

#permalink: /:year/:month/:title
permalink: /:title

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

gems:
  - jekyll-sitemap

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - bin
